### ISSUE TITLE
using boards for incompatible apps does not work properly

### ISSUE THREAD

**Issue by BytesGalore** [riot-appstore/rapstore-django#17]
how to reproduce:
choose an app incompatible for a board, e.g. `ARDUINO_HELLO_WORLD`
choose an incompatible board, e.g. `msba2`
click `download binary file`

expected would be to receive an error or similar
actual you see `Load` and nothing more happens

**Comment by jia200x** [comment]
addressed by #21

**Comment by jia200x** [comment]
fixed!
